spring:
  datasource:
      include:
      - docker
  #   - local

jpa:
  hibernate:
    ddl-auto : create
  database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
  properties:
    hibernate:
      format_sql: ture
      use_sql_comments: true
    show_sql : ture

logging:
  level:
    org:
      hibernate: info